debug: ${DEBUG_LOG:@debug.properties@}
trace: ${TRACE_LOG:@trace.properties@}
logging:
   level:
      org.springframework.data.mongodb: INFO
      org.springframework.data.mongodb.core.MongoTemplate: INFO
      org.springframework.test.context.support: INFO
      org.springframework.context.annotation: INFO
      org.springframework.test: INFO
      s7.Application: WARN
server:
   port: ${SERVER_PORT:8181}
   compression:
      enabled: true
      min-response-size: 1
   undertow:
      accesslog:
         dir: logs
         enabled: false
         pattern: '%t %a "%r" %s (%D ms)'
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
hystrix:
   shareSecurityContext: true
   command:
      default:
         execution:
            isolation:
               thread:
                  timeoutInMilliseconds: 6000
spring:
   profiles:
      active: dev
   application:
      name: '@projet.artifactId@'
   data:
      mongodb:
         authentication-database: "admin"
         database: "test"
         host: "localhost"
         password: "112358"
         username: "root"
         port: 27017